package com.sourcey.survey.FormThirteen;

public class ListOFPoliticalarties {

    public static String [] policalParties = new String []{
            "All Pakistan Muslim League",
            "Awami Justice Party Pakistan",
            "Awami Muslim League Pakistan",
            "Awami National Party",
            "Awami Workers Party",
            "Bahawalpur National Awami Party",
            "Balochistan National Party (Awami)",
            "Balochistan National Party",
            "Hazara Democratic Party",
            "Independent","Islami Tehreek Pakistan",
            "Jamaat-e-Islami Pakistan",
            "Jamhoori Wattan Party",
            "Jamiat Ulama-e-Islam (Fazal Ur Rehman)",
            "Jamiat Ulama-e-Islam Nazryati Pakistan",
            "Jamiat Ulama-e-Islam (Sami -ul-Haq)",
            "Jamiat Ulma-e-Pakistan (Noorani)",
            "Jamote Qami Movement",
            "Jannat Pakistan Party",
            "Majlis-e-Wahdat-e-Muslimeen Pakistan",
            "Mohajar Qaumi Movement Pakistan",
            "Mohib-e-Wattan Nowjawan Inqilabion Ki Anjuman",
            "Mustaqbil Pakistan",
            "Mutahidda Qabil Party",
            "Muttahidda Qaumi Movement",
            "National Party",
            "National Peoples Party",
            "Pakistan Conservative Party",
            "Pakistan Falah Party",
            "Pakistan Human Rights Party",
            "Pakistan Muhafiz Watan Party",
            "Pakistan Muslim League Council",
            "Pakistan Muslim League (Functional)",
            "Pakistan Muslim League (Nawaz)",
            "Pakistan Muslim League",
            "Pakistan Muslim League (Sher-e-Bangal) A.K. Fazal-Ul-Haque)",
            "Pakistan Muslim League (Zia)",
            "Pakistan National Muslim League",
            "Pakistan Peoples Party Parliamentarians",
            "Pakistan Peoples Party (Shaheed Bhutto)",
            "Pakistan Sunni Tehreek",
            "Pakistan Tehreek-e-Insaf",
            "Qaumi Watan Party (Sherpao)",
            "Sindh United Party",
            "Sunni Ittehad Council",
            "Tehreek-e-Suba Hazara",
            "Tehreek-e-Tahaffuze Pakistan",
            "Tehreek Tabdili Nizam Pakistan",
            "Pakistan Awami Tehreek",
            "Nizam-e-Mustafa Party",
            "Sunni Tehreek",
            "Balochistan National Movement",
            "Pakistan Citizen Movement",
            "Pakistan Aman Party",
            "Pasban",
            "Pakistan Muslim League Jinnah",
            "Pakistan Rah-e-Haq Party",
            "Peoples Muslim League Pakistan",
            "Markazi Jamiat Al- Hadith (Sajid Mir)",
            "Pakistan People's Party",
            "Tehreek-e-Labaik Pakistan",
            "Front National Pakistan",
            "Allah-o-Akbar Tehreek",
            "Aam Admi Tehreek Pakistan",
            "Aam Awam Party",
            "Aam Loeg Ittehad",
            "Aam Log Party Pakistan",
            "All Pakistan Minorities Alliance",
            "All Pakistan Minority Movement",
            "All Pakistan Muslim League - Jinnah",
            "All Pakistan Tehreek",
            "Amun Taraqqi Party",
            "Awam League",
            "Barabri Party Pakistan",
            "Humdardan-e-Watan Pakistan",
            "Masih Awami Party",
            "Mutihida League",
            "Muttahidda Ulema-e-Mashaikh Council of Pakistan",
            "National Peace Council Party",
            "Pak Sarzameen Party","Pakistan Aman Tehreek","Pakistan Awami Raj","Pakistan Barabri Party",
            "Pakistan Falahi Tehreek","Pakistan Freedom Movement","Pakistan Human Party",
            "Pakistan Islamic Republican Party","Pakistan Justice & Democratic Party",
            "Pakistan Kissan Ittehad (Ch. Anwar)","Pakistan Masiha Party","Pakistan Muslim Alliance",
            "Pakistan Peoples Party Workers","Pakistan Supreme Democratic Party","Pakistan Tehreek-e-Ijtihad",
            "Pakistan Tehreek-e-Insaf Nazriati","Pakistan Tehreek-e-Insaniat","Pakistan Welfare Party",
            "Pakistan Yaqeen Party","Pashtoonkhwa Milli Awami Party","Peoples Movement of Pakistan",
            "Roshan Pakistan League","Tabdeeli Pasand Party","Tehreek Ahle-e-Sunnat Pakistan",
            "Tehreek Jawanan Pakistan","Tehreek-e-Difa-e-Pakistan","Tehreek-e-Ehsas-e-Pakistan",
            "Tehreek-e-Labbaik Islam","Islami Jamhoori Ittehad Pakistan","Ittehad-e-Ummat Pakistan",
            "Pakistan Awami League","Pakistan Quami Yakjehti Party","Awami Party Pakistan-S",
            "Balochistan Awami Party","Pakistan Tehreek-e-Insaf-Gulalai","Move on Pakistan",
            "Saraikistan Democratic Party","Pakistan Muslim League Organization",
            "Pakistan Awami Inqelabi League",
            "Pakistan Muslim League (Junejo)",
            "Pakistan Muslim League (S)"
    };

}
