package com.sourcey.survey.FormThirteen;

public class ListOFDistricts {

    String [] strings = new String [] {"1", "2" };
    public static String [] districtsList = new String []{
            "Chitral",
            "Swat",
            "Upper Dir",
            "Lower Dir",
            "Malakand",
            "Buner",
            "Shangla",
            "Kohistan",
            "Batagram",
            "Mansehra",
            "Tor Ghar",
            "Abbottabad",
            "Haripur",
            "Swabi",
            "Mardan",
            "Charsadda",
            "Nowshera",
            "Peshawar",
            "Kohat",
            "Hangu",
            "Karak",
            "Bannu",
            "Lakki Marwat",
            "Tank",
            "Dera Ismail Khan",
            "Bajaur Agency",
            "Mohmand Agency",
            "Khyber Agency",
            "Kurram Agency",
            "Orakzai Agency",
            "North Waziristan Agency",
            "South Waziristan Agency",
            "Islamabad",
            "Attock",
            "Rawalpindi",
            "Chakwal",
            "Jhelum",
            "Gujrat",
            "Sialkot",
            "Narowal",
            "Gujranwala",
            "Mandi Bahauddin",
            "Hafizabad",
            "Sargodha",
            "Khushab",
            "Mianwali",
            "Bhakkar",
            "Chiniot",
            "Faisalabad",
            "Toba Tek Singh",
            "Jhang",
            "Nankana Sahib",
            "Sheikhupura",
            "Lahore",
            "Kasur",
            "Okara",
            "Pakpattan",
            "Sahiwal",
            "Khanewal",
            "Multan",
            "Lodhran",
            "Vehari",
            "Bahawalnagar",
            "Bahawalpur",
            "Rahim Yar Khan",
            "Muzaffargarh",
            "Layyah",
            "Dera Ghazi Khan",
            "Rajanpur",
            "Jacobabad",
            "Kashmore",
            "Shikarpur",
            "Larkana",
            "Kamber Shahdadkot",
            "Ghotki",
            "Sukkur",
            "Khairpur",
            "Naushero Feroz",
            "Shaheed Benazirabad",
            "Sanghar",
            "Mirpurkhas",
            "Umerkot",
            "Tharparkar",
            "Matiari",
            "Tando Allahyar",
            "Hyderabad",
            "Tando Muhammad Khan",
            "Badin",
            "Sujawal",
            "Thatta",
            "Jamshoro",
            "Dadu",
            "Malir",
            "Korangi",
            "Karachi East",
            "Karachi South",
            "Karachi West",
            "Karachi Central",
            "Killa Saifullah",
            "Zhob",
            "Sherani",
            "Loralai",
            "Musakhel",
            "Ziarat",
            "Harnai",
            "Dera Bugti",
            "Kohlu",
            "Barkhan",
            "Sibi",
            "Lehri",
            "Nasirabad",
            "Kachhi",
            "Jhal Magsi",
            "Jaffarabad",
            "Sohbatpur",
            "Pishin",
            "Killa Abdullah",
            "Quetta",
            "Mastung",
            "Kalat",
            "Chagai",
            "Nushki",
            "Kharan",
            "Khuzdar",
            "Panjgur",
            "Washuk",
            "Awaran",
            "Kech",
            "Lasbela",
            "Gwadar"
    };
}
